### ISSUE TITLE
Error while sending message or call to target

### ISSUE THREAD

**Issue by mohammad-sajid** [linkedin/iris#669] opened 2022-02-13 16:05 UTC
While sending a call r message to target am getting the below error. 
As verified in the target table the details were there and the mode was also proper for that target. but still getting the error. 

2022-02-14 11:47:58,074 ERROR iris.sender.shared failed modifying nonexistent metric: ‘plivocall_cnt’
Traceback (most recent call last):
 File “sender.py”, line 1292, in fetch_and_send_message
   success, sent_locally = distributed_send_message(message, vendor_manager)
 File “sender.py”, line 1182, in distributed_send_message
   runtime = vendor_manager.send_message(message)
 File “/usr/local/lib/python3.8/dist-packages/iris/vendors/__init__.py”, line 61, in send_message
   for tries, vendor in enumerate(self.app_specific_vendors_iter.get(message.get(‘application’), self.vendors_iter)[message[‘mode’]]):
KeyError: ‘plivocall’
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File “/usr/local/lib/python3.8/dist-packages/iris/sender/shared.py”, line 15, in add_mode_stat
   stats[mode + ‘_cnt’] += 1
KeyError: ‘plivocall_cnt’
2022-02-14 11:47:58,075 ERROR root reclassifying as email

below are the target_contact & mode details. 

**mode**
+----+-----------+
| id | name      |
+----+-----------+
| 26 | call      |
| 36 | drop      |
| 35 | email     |
| 37 | plivocall |
| 17 | slack     |
|  8 | sms       |
+----+-----------+

**target_contact**
+-----------+---------+-------------------------------+
| target_id | mode_id | destination                   |
+-----------+---------+-------------------------------+
|       348 |       8 | +91 95057 XXXXX               |
|       348 |      17 | sajid                         |
|       348 |      26 | +91 95057 XXXXX               |
|       348 |      35 | mdsajid@test.com |
|       348 |      37 | +91 95057 XXXXX               |
+-----------+---------+-------------------------------+

**Comment by mohammad-sajid** [comment] 2022-02-16 01:35
@diegocepedaw  Yes it's there in the applications and also in DB. 
![image](https://user-images.githubusercontent.com/57441817/154179430-619d630e-ed7b-40a2-b13c-620f855a4ec5.png)

**Comment by mohammad-sajid** [comment] 2022-03-15 07:03
@diegocepedaw  getting **You are receiving this as you created this plan and we can’t resolve oncall-primary of NOC-Team at this time.** error. 

Also, i can see in body priority passing as low while testing it from Plan directly. 

can you please help here?

{‘body’: “You are receiving this as you created this plan and we can’t resolve oncall-primary of NOC-Team at this time.\n\n”, ‘message_id’: 50, ‘target’: ‘admin’, ‘priority’: ‘low’, ‘priority_id’: 35, ‘application’: ‘oncall-stg’, ‘plan’: ‘nagios-freshdesk-service-plan’, ‘plan_id’: 66, ‘incident_id’: 533326, ‘context’: {‘test’: None, ‘iris’: {‘body’: “You are receiving this as you created this plan and we can’t resolve oncall-primary of NOC-Team at this time.\n\n”, ‘message_id’: 50, ‘target’: ‘admin’, ‘priority’: ‘low’, ‘priority_id’: 35, ‘application’: ‘oncall-stg’, ‘plan’: ‘nagios-freshdesk-service-plan’, ‘plan_id’: 66, ‘incident_id’: 533326, ‘incident_created’: datetime.datetime(2022, 3, 15, 5, 55, 49), ‘template’:‘nagios-freshdesk-service-template’, ‘dynamic_target’: None}}, ‘incident_created’: datetime.datetime(2022, 3, 15, 5, 55, 49), ‘template’: ‘nagios-freshdesk-service-template’, ‘dynamic_target’: None}


![image](https://user-images.githubusercontent.com/57441817/158323924-73e30de2-7261-4f01-83d1-c5132ae1b87d.png)

**Comment by allwyn-pradip** [comment] 2022-04-20 13:28
@mohammad-sajid pls close this as the issue is resolved using #690

**Closed** 2022-04-20 13:44 UTC
